import { exec } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";

const execAsync = promisify(exec);
const PAGE_SIZE = 5000;

type JsonRecord = Record<string, unknown>;

function arg(name: string) {
  const inline = process.argv.find((item) => item.startsWith(`--${name}=`));
  if (inline) return inline.slice(name.length + 3);
  const index = process.argv.indexOf(`--${name}`);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

function hasFlag(name: string) {
  return process.argv.includes(`--${name}`);
}

function assertUuid(value: string | undefined, name: string) {
  if (!value || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) {
    throw new Error(`Missing or invalid ${name}.`);
  }
  return value;
}

function parseCliJson(stdout: string) {
  const start = stdout.indexOf("{");
  const end = stdout.lastIndexOf("}");
  if (start < 0 || end < start) throw new Error(`Unable to parse Supabase CLI JSON output: ${stdout.slice(0, 200)}`);
  return JSON.parse(stdout.slice(start, end + 1)) as { rows?: Array<Record<string, unknown>> };
}

async function runSql(sql: string) {
  const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "quiksol-supabase-restore-"));
  const sqlPath = path.join(tempDir, "query.sql");
  try {
    await fs.writeFile(sqlPath, sql, "utf8");
    const escapedSqlPath = `"${sqlPath.replace(/"/g, '\\"')}"`;
    const { stdout } = await execAsync(`npx supabase db query --linked --file ${escapedSqlPath}`, {
      maxBuffer: 1024 * 1024 * 50
    });
    return parseCliJson(stdout);
  } finally {
    await fs.rm(tempDir, { recursive: true, force: true }).catch(() => undefined);
  }
}

function sqlLiteral(value: string) {
  return `'${value.replace(/'/g, "''")}'`;
}

function parseJsonCell(value: unknown) {
  if (typeof value === "string") return JSON.parse(value) as JsonRecord;
  if (value && typeof value === "object") return value as JsonRecord;
  return {};
}

async function loadRestoreReport(reportPath: string, jobId: string) {
  const absolutePath = path.resolve(process.cwd(), reportPath);
  const report = JSON.parse(await fs.readFile(absolutePath, "utf8")) as JsonRecord;
  const diagnostics = parseJsonCell(report.diagnostics);
  const reportJobId = String(diagnostics.jobId ?? "");
  const uploadBatchId = assertUuid(String(diagnostics.uploadBatchId ?? ""), "report uploadBatchId");
  if (reportJobId !== jobId) {
    throw new Error(`Report jobId mismatch. Expected ${jobId}, got ${reportJobId || "empty"}.`);
  }
  if (report.mode !== "backup_before_soft_archive") {
    throw new Error("Restore requires a backup_before_soft_archive report generated by cleanup --apply.");
  }

  const candidates = Array.isArray(report.candidates) ? report.candidates : [];
  const ids = candidates
    .map((candidate) => (candidate && typeof candidate === "object" ? String((candidate as JsonRecord).id ?? "") : ""))
    .filter((id) => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id));
  if (!ids.length) throw new Error("Report does not contain restore candidate IDs.");
  if (ids.length !== candidates.length) throw new Error("Report contains invalid candidate IDs; no records were restored.");

  return {
    reportPath: absolutePath,
    uploadBatchId,
    ids
  };
}

function idsCte(ids: string[]) {
  return `
    with restore_ids as (
      select value::uuid as id
      from jsonb_array_elements_text(${sqlLiteral(JSON.stringify(ids))}::jsonb)
    )
  `;
}

async function countRestoreCandidates(uploadBatchId: string, ids: string[]) {
  let archivedMatches = 0;
  let activeMatches = 0;
  let wrongBatchMatches = 0;

  for (let offset = 0; offset < ids.length; offset += PAGE_SIZE) {
    const page = ids.slice(offset, offset + PAGE_SIZE);
    const sql = `
      ${idsCte(page)}
      select jsonb_build_object(
        'archivedMatches', count(*) filter (
          where br.upload_batch_id = ${sqlLiteral(uploadBatchId)}::uuid
            and br.archived_at is not null
        ),
        'activeMatches', count(*) filter (
          where br.upload_batch_id = ${sqlLiteral(uploadBatchId)}::uuid
            and br.archived_at is null
        ),
        'wrongBatchMatches', count(*) filter (
          where br.id is not null
            and br.upload_batch_id <> ${sqlLiteral(uploadBatchId)}::uuid
        )
      ) as counts
      from restore_ids ids
      left join public.business_records br on br.id = ids.id;
    `;
    const result = await runSql(sql);
    const counts = parseJsonCell(result.rows?.[0]?.counts);
    archivedMatches += Number(counts.archivedMatches ?? 0);
    activeMatches += Number(counts.activeMatches ?? 0);
    wrongBatchMatches += Number(counts.wrongBatchMatches ?? 0);
  }

  return { archivedMatches, activeMatches, wrongBatchMatches };
}

async function restorePage(uploadBatchId: string, ids: string[]) {
  const sql = `
    ${idsCte(ids)}
    , restored as (
      update public.business_records br
      set archived_at = null
      from restore_ids ids
      where br.id = ids.id
        and br.upload_batch_id = ${sqlLiteral(uploadBatchId)}::uuid
        and br.archived_at is not null
      returning br.id
    )
    select jsonb_build_object('restoredRecords', count(*)) as result
    from restored;
  `;
  const result = await runSql(sql);
  const payload = parseJsonCell(result.rows?.[0]?.result);
  return Number(payload.restoredRecords ?? 0);
}

async function restoreCandidates(uploadBatchId: string, ids: string[]) {
  let restoredRecords = 0;
  for (let offset = 0; offset < ids.length; offset += PAGE_SIZE) {
    restoredRecords += await restorePage(uploadBatchId, ids.slice(offset, offset + PAGE_SIZE));
  }
  return restoredRecords;
}

async function main() {
  const jobId = assertUuid(arg("jobId") ?? arg("job-id"), "jobId");
  const fromReport = arg("fromReport") ?? arg("from-report");
  if (!fromReport) throw new Error("Missing --fromReport=<backup-report.json>.");
  const apply = hasFlag("apply");
  if (apply && hasFlag("dry-run")) throw new Error("Use either --dry-run or --apply, not both.");

  const report = await loadRestoreReport(fromReport, jobId);
  const counts = await countRestoreCandidates(report.uploadBatchId, report.ids);
  const summary = {
    jobId,
    uploadBatchId: report.uploadBatchId,
    reportPath: report.reportPath,
    candidateIdsInReport: report.ids.length,
    archivedMatchesToRestore: counts.archivedMatches,
    alreadyActiveMatches: counts.activeMatches,
    wrongBatchMatches: counts.wrongBatchMatches
  };

  if (!apply) {
    console.log(JSON.stringify({
      mode: "dry-run",
      ...summary,
      restoreSafe: counts.wrongBatchMatches === 0,
      recommendedAction: counts.archivedMatches > 0
        ? "Run restore with --apply only if this backup report corresponds to the cleanup you want to revert."
        : "No archived matching records were found to restore."
    }, null, 2));
    return;
  }

  if (counts.wrongBatchMatches > 0) {
    throw new Error("Restore report contains IDs outside the target upload_batch_id; no records were restored.");
  }

  const restoredRecords = await restoreCandidates(report.uploadBatchId, report.ids);
  console.log(JSON.stringify({
    mode: "apply",
    ...summary,
    restoredRecords,
    note: "Restore only clears archived_at for IDs listed in the backup report and matching the target upload_batch_id."
  }, null, 2));
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : JSON.stringify(error));
  process.exit(1);
});
