import { loadEnvConfig } from "@next/env";
import { PostgrestClient } from "@supabase/postgrest-js";
import fs from "node:fs/promises";
import path from "node:path";
import { getSupabaseServiceRoleKey } from "../lib/security/env";

loadEnvConfig(process.cwd());

const PAGE_SIZE = 500;

type JsonRecord = Record<string, unknown>;
type DatabaseClient = PostgrestClient;

function arg(name: string) {
  const inline = process.argv.find((item) => item.startsWith(`--${name}=`));
  if (inline) return inline.slice(name.length + 3);
  const index = process.argv.indexOf(`--${name}`);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

function hasFlag(name: string) {
  return process.argv.includes(`--${name}`);
}

function assertUuid(value: string | undefined, name: string) {
  if (!value || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) {
    throw new Error(`Missing or invalid ${name}.`);
  }
  return value;
}

function safeErrorMessage(error: unknown) {
  const value = error instanceof Error ? error.message : JSON.stringify(error);
  return String(value ?? "Unknown error").slice(0, 800);
}

function parseJsonCell(value: unknown) {
  if (typeof value === "string") return JSON.parse(value) as JsonRecord;
  if (value && typeof value === "object") return value as JsonRecord;
  return {};
}

function createServiceClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = getSupabaseServiceRoleKey();
  if (!url || !key) {
    throw new Error("Missing NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY/SUPABASE_SECRET_KEY.");
  }
  return new PostgrestClient(`${url.replace(/\/$/, "")}/rest/v1`, {
    headers: {
      apikey: key,
      Authorization: `Bearer ${key}`
    }
  });
}

async function loadRestoreReport(reportPath: string, jobId: string) {
  const absolutePath = path.resolve(process.cwd(), reportPath);
  const report = JSON.parse(await fs.readFile(absolutePath, "utf8")) as JsonRecord;
  const diagnostics = parseJsonCell(report.diagnostics);
  const reportJobId = String(diagnostics.jobId ?? "");
  const uploadBatchId = assertUuid(String(diagnostics.uploadBatchId ?? ""), "report uploadBatchId");
  if (reportJobId !== jobId) {
    throw new Error(`Report jobId mismatch. Expected ${jobId}, got ${reportJobId || "empty"}.`);
  }
  if (report.mode !== "backup_before_soft_archive") {
    throw new Error("Restore requires a backup_before_soft_archive report generated by cleanup --apply.");
  }

  const candidates = Array.isArray(report.candidates) ? report.candidates : [];
  const ids = candidates
    .map((candidate) => (candidate && typeof candidate === "object" ? String((candidate as JsonRecord).id ?? "") : ""))
    .filter((id) => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id));
  if (!ids.length) throw new Error("Report does not contain restore candidate IDs.");
  if (ids.length !== candidates.length) throw new Error("Report contains invalid candidate IDs; no records were restored.");

  return {
    reportPath: absolutePath,
    uploadBatchId,
    ids
  };
}

async function countRestoreCandidates(supabase: DatabaseClient, uploadBatchId: string, ids: string[]) {
  let archivedMatches = 0;
  let activeMatches = 0;
  let wrongBatchMatches = 0;

  for (let offset = 0; offset < ids.length; offset += PAGE_SIZE) {
    const page = ids.slice(offset, offset + PAGE_SIZE);
    const result = await supabase
      .from("business_records")
      .select("id,upload_batch_id,archived_at")
      .in("id", page);
    if (result.error) throw result.error;
    for (const record of result.data ?? []) {
      if (record.upload_batch_id !== uploadBatchId) {
        wrongBatchMatches += 1;
      } else if (record.archived_at === null) {
        activeMatches += 1;
      } else {
        archivedMatches += 1;
      }
    }
  }

  return { archivedMatches, activeMatches, wrongBatchMatches };
}

async function restoreCandidates(supabase: DatabaseClient, uploadBatchId: string, ids: string[]) {
  let restoredRecords = 0;
  for (let offset = 0; offset < ids.length; offset += PAGE_SIZE) {
    const page = ids.slice(offset, offset + PAGE_SIZE);
    const result = await supabase
      .from("business_records")
      .update({ archived_at: null })
      .eq("upload_batch_id", uploadBatchId)
      .not("archived_at", "is", null)
      .in("id", page)
      .select("id");
    if (result.error) throw result.error;
    restoredRecords += result.data?.length ?? 0;
  }
  return restoredRecords;
}

async function main() {
  let mutationStarted = false;
  try {
    const jobId = assertUuid(arg("jobId") ?? arg("job-id"), "jobId");
    const fromReport = arg("fromReport") ?? arg("from-report");
    if (!fromReport) throw new Error("Missing --fromReport=<backup-report.json>.");
    const apply = hasFlag("apply");
    if (apply && hasFlag("dry-run")) throw new Error("Use either --dry-run or --apply, not both.");

    const report = await loadRestoreReport(fromReport, jobId);
    const supabase = createServiceClient();
    const counts = await countRestoreCandidates(supabase, report.uploadBatchId, report.ids);
    const summary = {
      jobId,
      uploadBatchId: report.uploadBatchId,
      reportPath: report.reportPath,
      candidateIdsInReport: report.ids.length,
      archivedMatchesToRestore: counts.archivedMatches,
      alreadyActiveMatches: counts.activeMatches,
      wrongBatchMatches: counts.wrongBatchMatches
    };

    if (!apply) {
      console.log(JSON.stringify({
        mode: "dry-run",
        ...summary,
        restoreSafe: counts.wrongBatchMatches === 0,
        recommendedAction: counts.archivedMatches > 0
          ? "Run restore with --apply only if this backup report corresponds to the cleanup you want to revert."
          : "No archived matching records were found to restore."
      }, null, 2));
      return;
    }

    if (counts.wrongBatchMatches > 0) {
      throw new Error("Restore report contains IDs outside the target upload_batch_id; no records were restored.");
    }

    mutationStarted = true;
    const restoredRecords = await restoreCandidates(supabase, report.uploadBatchId, report.ids);
    console.log(JSON.stringify({
      mode: "apply",
      ...summary,
      restoredRecords,
      note: "Restore only clears archived_at for IDs listed in the backup report and matching the target upload_batch_id."
    }, null, 2));
  } catch (error) {
    console.error(safeErrorMessage(error));
    if (!mutationStarted) console.error("No records were modified.");
    else console.error("Mutation started before the failure. Verify current DB state before retrying.");
    process.exit(1);
  }
}

main();
